package com.bookmarklocker.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable // Import Serializable

/**
 * Collection: A data class representing a user-defined collection (folder) for bookmarks.
 * This class is annotated as a Room Entity, mapping to a table in the database.
 * Each collection has a unique ID, a name, and a color associated with it for quick reference.
 *
 * Implemented Serializable in Step 5 to allow easy conversion to/from JSON for backup/restore.
 *
 * @param id Unique identifier for the collection. Auto-generated by Room.
 * @param name The name of the collection (e.g., "Work Links", "Recipes").
 * @param color A string representing the color of the collection (e.g., "#FF00FF" or a color name).
 * This can be used to visually distinguish collections.
 * @param createdAt The timestamp when the collection was created, in milliseconds since epoch.
 */
@Entity(tableName = "collections")
data class Collection(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "color")
    val color: String,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
) : Serializable // Make Collection class Serializable
